/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.TheTapDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.TheTap;

/**
 *
 * @author locmi
 */
public class addTheTap extends javax.swing.JFrame {
    private TheTapForm panel;
    /**
     * Creates new form addTheTap
     */
    public addTheTap(TheTapForm panel) {
        initComponents();
        this.panel = panel;
        tf_MATTAP.setEditable(false);
        setLocationRelativeTo(null);
        tf_MATTAP.setText(generateIdTTap());
    }
    
    public String generateIdTTap() {
        // Lấy danh sách tất cả các thẻ tập
        ArrayList<TheTap> ttapAll = TheTapDAO.getInstance().selectAll();

        // Nếu danh sách trống, bắt đầu từ TT001
        if (ttapAll.isEmpty()) {
            return "TT001";
        }

        int maxId = 0;
        // Tìm ID lớn nhất
        for (TheTap ttap : ttapAll) {
            String id = ttap.getId_TTap().substring(2); // Bỏ "TT" ở đầu
            int idNumber = Integer.parseInt(id);
            if (idNumber > maxId) {
                maxId = idNumber;
            }
        }

        // Tạo ID mới lớn hơn ID lớn nhất một đơn vị
        int newIdNumber = maxId + 1;
        return String.format("TT%03d", newIdNumber);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_MATB = new javax.swing.JLabel();
        tf_MATTAP = new javax.swing.JTextField();
        lb_TENTB = new javax.swing.JLabel();
        tf_MAKH = new javax.swing.JTextField();
        lb_SOLUONG = new javax.swing.JLabel();
        tf_MAGT = new javax.swing.JTextField();
        bt_Them = new javax.swing.JButton();
        bt_Huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 239, 237));

        jPanel2.setBackground(new java.awt.Color(251, 129, 54));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM THÔNG TIN THẺ TẬP");
        jLabel1.setToolTipText("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
        );

        lb_MATB.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_MATB.setText("Mã thẻ tập");

        tf_MATTAP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_MATTAPActionPerformed(evt);
            }
        });

        lb_TENTB.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_TENTB.setText("Mã khách hàng");

        tf_MAKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_MAKHActionPerformed(evt);
            }
        });

        lb_SOLUONG.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_SOLUONG.setText("Mã gói tập");

        tf_MAGT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_MAGTActionPerformed(evt);
            }
        });

        bt_Them.setBackground(new java.awt.Color(251, 129, 54));
        bt_Them.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        bt_Them.setForeground(new java.awt.Color(255, 255, 255));
        bt_Them.setText("Thêm");
        bt_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_ThemActionPerformed(evt);
            }
        });

        bt_Huy.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        bt_Huy.setForeground(new java.awt.Color(251, 129, 54));
        bt_Huy.setText("Hủy");
        bt_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lb_MATB)
                    .addComponent(tf_MATTAP)
                    .addComponent(lb_TENTB)
                    .addComponent(tf_MAKH, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_MAGT)
                    .addComponent(lb_SOLUONG))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(lb_MATB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_MATTAP, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_TENTB)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_MAKH, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_SOLUONG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_MAGT, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Huy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_MATTAPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_MATTAPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MATTAPActionPerformed

    private void tf_MAKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_MAKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MAKHActionPerformed

    private void tf_MAGTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_MAGTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_MAGTActionPerformed

    private void bt_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_ThemActionPerformed
        String id_Ttap = tf_MATTAP.getText();
        String id_KH = tf_MAKH.getText();
        String id_GT = tf_MAGT.getText();
        
        if (id_Ttap.isEmpty() || id_KH.isEmpty() || id_GT.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống thông tin", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        
        if (TheTapDAO.getInstance().selectById(id_KH) != null) {
            JOptionPane.showMessageDialog(this, "Khách hàng đã có thẻ tập!", "Cảnh báo!", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        TheTap ttap = new TheTap(id_Ttap, id_KH, id_GT, null, null);
        try {
            TheTapDAO.getInstance().insert(ttap);
            panel.loadDataToTable(TheTapDAO.getInstance().selectAll());
            JOptionPane.showMessageDialog(this, "Đăng ký gói tập thành công!");
            this.dispose();
            
        } catch (RuntimeException e) {
            String errorMessage = e.getMessage();
            if (errorMessage.contains("Không tìm thấy hoặc khách hàng đã bị xóa.")) {
                JOptionPane.showMessageDialog(this, "Khách hàng không tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            else if (errorMessage.contains("Không tìm thấy hoặc gói tập đã bị xóa.")) {
                JOptionPane.showMessageDialog(this, "Gói tập không tồn tại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            else if (errorMessage.contains("Mỗi khách hàng chỉ được phép có 1 thẻ tập")) {
                JOptionPane.showMessageDialog(this, "Khách hàng đã có thẻ tập rồi!", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
            else {
                JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + errorMessage, "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }

        
    }//GEN-LAST:event_bt_ThemActionPerformed

    private void bt_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_HuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_HuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TheTapForm panel = new TheTapForm();
                new addTheTap(panel).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Huy;
    private javax.swing.JButton bt_Them;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_MATB;
    private javax.swing.JLabel lb_SOLUONG;
    private javax.swing.JLabel lb_TENTB;
    private javax.swing.JTextField tf_MAGT;
    private javax.swing.JTextField tf_MAKH;
    private javax.swing.JTextField tf_MATTAP;
    // End of variables declaration//GEN-END:variables
}
