/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.ThanhToanDAO;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.ThanhToan;

/**
 *
 * @author locmi
 */
public class addThanhToan extends javax.swing.JFrame {
    private ThanhToanForm panel;

    /**
     * Creates new form addThanhToan
     * @param panel
     */
    public addThanhToan(ThanhToanForm panel) {
        this.panel = panel;
        initComponents();
        setSize(390, 579);
        setLocationRelativeTo(null);
        tf_MATTOAN.setEditable(false);
        tf_MATTOAN.setText(generateIdTTOAN());
    }
    
    public String generateIdTTOAN() {
        // Lấy danh sách tất cả các thanh toán
        ArrayList<ThanhToan> ttoanAll = ThanhToanDAO.getInstance().selectAll();

        int i = ttoanAll.size();
        String check = "check";

        while (check.length() != 0) {
            i++;
            for (ThanhToan ttoan : ttoanAll) {
                if (ttoan.getId_TTOAN().equals("T00" + i)) {
                    check = "";
                }
            }
            if (check.length() == 0) {
                check = "check";
            } else {
                check = "";
            }
        }

        return "T00" + i;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_MANV = new javax.swing.JLabel();
        tf_MATTOAN = new javax.swing.JTextField();
        lb_TENDN = new javax.swing.JLabel();
        tf_MAKH = new javax.swing.JTextField();
        lb_MATKHAU = new javax.swing.JLabel();
        tf_MANV = new javax.swing.JTextField();
        bt_AddTAIKHOAN = new javax.swing.JButton();
        bt_Huy = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 239, 237));

        jPanel2.setBackground(new java.awt.Color(251, 129, 54));
        jPanel2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM MỚI THANH TOÁN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        lb_MANV.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_MANV.setText("Mã thanh toán");

        lb_TENDN.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_TENDN.setText("Mã khách hàng");

        lb_MATKHAU.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_MATKHAU.setText("Mã nhân viên thực hiện");

        bt_AddTAIKHOAN.setBackground(new java.awt.Color(251, 129, 54));
        bt_AddTAIKHOAN.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        bt_AddTAIKHOAN.setForeground(new java.awt.Color(255, 255, 255));
        bt_AddTAIKHOAN.setText("Thêm");
        bt_AddTAIKHOAN.setPreferredSize(new java.awt.Dimension(64, 22));
        bt_AddTAIKHOAN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_AddTAIKHOANMouseClicked(evt);
            }
        });

        bt_Huy.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        bt_Huy.setForeground(new java.awt.Color(251, 129, 54));
        bt_Huy.setText("Hủy");
        bt_Huy.setPreferredSize(new java.awt.Dimension(64, 22));
        bt_Huy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_HuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_MATKHAU)
                    .addComponent(lb_TENDN)
                    .addComponent(lb_MANV)
                    .addComponent(tf_MATTOAN)
                    .addComponent(tf_MAKH)
                    .addComponent(tf_MANV, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(bt_AddTAIKHOAN, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bt_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(79, 79, 79)
                .addComponent(lb_MANV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_MATTOAN, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_TENDN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_MAKH, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lb_MATKHAU)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_MANV, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_AddTAIKHOAN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bt_Huy, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 116, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_AddTAIKHOANMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_AddTAIKHOANMouseClicked
        String id_ttoan = tf_MATTOAN.getText();
        String id_KH = tf_MAKH.getText();
        String id_NV = tf_MANV.getText();
        if (id_ttoan.isEmpty() || id_KH.isEmpty() || id_NV.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ thông tin", "Cảnh báo", JOptionPane.WARNING_MESSAGE);            
        }
        if (ThanhToanDAO.getInstance().selectById(id_ttoan) == null) {
            try {
                ThanhToan ttoan = new ThanhToan(id_ttoan, id_KH, id_NV, null, 0, "Chưa thanh toán", null);
                ThanhToanDAO.getInstance().insert(ttoan);
                panel.loadDataToTable(ThanhToanDAO.getInstance().selectAll());
                JOptionPane.showMessageDialog(this, "Thêm thanh toán thành công!");
                this.dispose();
            } catch (RuntimeException e) {
                String errorMessage = e.getMessage();
                if (errorMessage.contains("Nhân viên không tồn tại")) {
                    JOptionPane.showMessageDialog(this, "Nhân viên không tồn tại", "Lỗi", JOptionPane.ERROR_MESSAGE);                    
                }
                else {
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi: " + errorMessage, "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        } else {
            JOptionPane.showMessageDialog(this, "Thanh toán đã tồn tại!", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_bt_AddTAIKHOANMouseClicked

    private void bt_HuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_HuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_bt_HuyActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThanhToanForm panel = new ThanhToanForm();
                new addThanhToan(panel).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_AddTAIKHOAN;
    private javax.swing.JButton bt_Huy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_MANV;
    private javax.swing.JLabel lb_MATKHAU;
    private javax.swing.JLabel lb_TENDN;
    private javax.swing.JTextField tf_MAKH;
    private javax.swing.JTextField tf_MANV;
    private javax.swing.JTextField tf_MATTOAN;
    // End of variables declaration//GEN-END:variables
}
