/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatLightLaf;
import java.awt.*;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import List.ListDM;
import  java.util.List;
import controller.Screen;
import java.util.ArrayList;


/**
 *
 * @author ADMIN
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        setSize(1086, 760);
        setLocationRelativeTo(null);
        setResizable(false);  
        Screen switchScreen = new Screen(jPanelContent);
        switchScreen.setView(pn_Home, jLabelHome);
        List<ListDM> listItem = new ArrayList<>();
        listItem.add(new ListDM("Home",pn_Home,jLabelHome));
        listItem.add(new ListDM("KhachHang",pn_KH,jLabelKhachHang));
        listItem.add(new ListDM("GoiTap",pn_GT,jLabelGT));
        listItem.add(new ListDM("HuanLuyenVien",pn_HLV,jLabelHLV));
        listItem.add(new ListDM("TheTap",pn_TrainCard,jLabelTheTap));
        listItem.add(new ListDM("Thue",pn_Thue,jLabelThue));
        listItem.add(new ListDM("ThietBi",pn_TB,jLabelThietBi));
        listItem.add(new ListDM("ThanhToan",pn_TT,jLabelThanhToan));
        listItem.add(new ListDM("ThongKe",pn_TK,jLabelThongKe));
        listItem.add(new ListDM("NhanVien",pn_NV,jLabelNhanVien));
        listItem.add(new ListDM("TaiKhoan",pn_TaiKhoan,jLabelTaiKhoan));
        
        switchScreen.setEvent(listItem);
    }
    
    
    /*
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        back = new javax.swing.JPanel();
        side = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        pn_Home = new javax.swing.JPanel();
        jLabelHome = new javax.swing.JLabel();
        pn_GT = new javax.swing.JPanel();
        jLabelGT = new javax.swing.JLabel();
        pn_KH = new javax.swing.JPanel();
        jLabelKhachHang = new javax.swing.JLabel();
        pn_HLV = new javax.swing.JPanel();
        jLabelHLV = new javax.swing.JLabel();
        pn_TB = new javax.swing.JPanel();
        jLabelThietBi = new javax.swing.JLabel();
        pn_TT = new javax.swing.JPanel();
        jLabelThanhToan = new javax.swing.JLabel();
        pn_Hello = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        pn_NV = new javax.swing.JPanel();
        jLabelNhanVien = new javax.swing.JLabel();
        pn_TrainCard = new javax.swing.JPanel();
        jLabelTheTap = new javax.swing.JLabel();
        pn_Thue = new javax.swing.JPanel();
        jLabelThue = new javax.swing.JLabel();
        pn_TK = new javax.swing.JPanel();
        jLabelThongKe = new javax.swing.JLabel();
        pn_TaiKhoan = new javax.swing.JPanel();
        jLabelTaiKhoan = new javax.swing.JLabel();
        pn_LogOut = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jPanelContent = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(255, 239, 237));
        back.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        back.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side.setBackground(new java.awt.Color(243, 197, 192));
        side.setPreferredSize(new java.awt.Dimension(200, 500));

        pn_Home.setBackground(new java.awt.Color(243, 197, 192));
        pn_Home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_HomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_HomeMouseExited(evt);
            }
        });

        jLabelHome.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Home.png"))); // NOI18N
        jLabelHome.setText("    Home");
        jLabelHome.setPreferredSize(new java.awt.Dimension(230, 0));
        jLabelHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelHomeMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout pn_HomeLayout = new javax.swing.GroupLayout(pn_Home);
        pn_Home.setLayout(pn_HomeLayout);
        pn_HomeLayout.setHorizontalGroup(
            pn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pn_HomeLayout.setVerticalGroup(
            pn_HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelHome, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        pn_GT.setBackground(new java.awt.Color(243, 197, 192));
        pn_GT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_GT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_GTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_GTMouseExited(evt);
            }
        });

        jLabelGT.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelGT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_TrainProgram.png"))); // NOI18N
        jLabelGT.setText("    Gói tập");
        jLabelGT.setPreferredSize(new java.awt.Dimension(230, 0));

        javax.swing.GroupLayout pn_GTLayout = new javax.swing.GroupLayout(pn_GT);
        pn_GT.setLayout(pn_GTLayout);
        pn_GTLayout.setHorizontalGroup(
            pn_GTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_GTLayout.createSequentialGroup()
                .addComponent(jLabelGT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_GTLayout.setVerticalGroup(
            pn_GTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelGT, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        pn_KH.setBackground(new java.awt.Color(243, 197, 192));
        pn_KH.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_KH.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_KHMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_KHMouseExited(evt);
            }
        });

        jLabelKhachHang.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelKhachHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Customer.png"))); // NOI18N
        jLabelKhachHang.setText("    Khách hàng");
        jLabelKhachHang.setPreferredSize(new java.awt.Dimension(230, 0));

        javax.swing.GroupLayout pn_KHLayout = new javax.swing.GroupLayout(pn_KH);
        pn_KH.setLayout(pn_KHLayout);
        pn_KHLayout.setHorizontalGroup(
            pn_KHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_KHLayout.createSequentialGroup()
                .addComponent(jLabelKhachHang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_KHLayout.setVerticalGroup(
            pn_KHLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        pn_HLV.setBackground(new java.awt.Color(243, 197, 192));
        pn_HLV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_HLVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_HLVMouseExited(evt);
            }
        });

        jLabelHLV.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelHLV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_PT.png"))); // NOI18N
        jLabelHLV.setText("    Huấn luyện viên");
        jLabelHLV.setPreferredSize(new java.awt.Dimension(230, 0));

        javax.swing.GroupLayout pn_HLVLayout = new javax.swing.GroupLayout(pn_HLV);
        pn_HLV.setLayout(pn_HLVLayout);
        pn_HLVLayout.setHorizontalGroup(
            pn_HLVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_HLVLayout.createSequentialGroup()
                .addComponent(jLabelHLV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_HLVLayout.setVerticalGroup(
            pn_HLVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_HLVLayout.createSequentialGroup()
                .addComponent(jLabelHLV, javax.swing.GroupLayout.DEFAULT_SIZE, 39, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_TB.setBackground(new java.awt.Color(243, 197, 192));
        pn_TB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_TBMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_TBMouseExited(evt);
            }
        });

        jLabelThietBi.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelThietBi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Devices.png"))); // NOI18N
        jLabelThietBi.setText("    Thiết bị");
        jLabelThietBi.setPreferredSize(new java.awt.Dimension(230, 0));

        javax.swing.GroupLayout pn_TBLayout = new javax.swing.GroupLayout(pn_TB);
        pn_TB.setLayout(pn_TBLayout);
        pn_TBLayout.setHorizontalGroup(
            pn_TBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TBLayout.createSequentialGroup()
                .addComponent(jLabelThietBi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_TBLayout.setVerticalGroup(
            pn_TBLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TBLayout.createSequentialGroup()
                .addComponent(jLabelThietBi, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_TT.setBackground(new java.awt.Color(243, 197, 192));
        pn_TT.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_TT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_TTMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_TTMouseExited(evt);
            }
        });

        jLabelThanhToan.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelThanhToan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Payment.png"))); // NOI18N
        jLabelThanhToan.setText("    Thanh toán");
        jLabelThanhToan.setPreferredSize(new java.awt.Dimension(230, 0));

        javax.swing.GroupLayout pn_TTLayout = new javax.swing.GroupLayout(pn_TT);
        pn_TT.setLayout(pn_TTLayout);
        pn_TTLayout.setHorizontalGroup(
            pn_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TTLayout.createSequentialGroup()
                .addComponent(jLabelThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_TTLayout.setVerticalGroup(
            pn_TTLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_TTLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelThanhToan, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addContainerGap())
        );

        pn_Hello.setBackground(new java.awt.Color(243, 197, 192));

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("HELLO HANDSOME!!");

        javax.swing.GroupLayout pn_HelloLayout = new javax.swing.GroupLayout(pn_Hello);
        pn_Hello.setLayout(pn_HelloLayout);
        pn_HelloLayout.setHorizontalGroup(
            pn_HelloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_HelloLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_HelloLayout.setVerticalGroup(
            pn_HelloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_HelloLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        pn_NV.setBackground(new java.awt.Color(243, 197, 192));
        pn_NV.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pn_NV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_NVMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_NVMouseExited(evt);
            }
        });

        jLabelNhanVien.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Employees.png"))); // NOI18N
        jLabelNhanVien.setText("    Nhân viên");
        jLabelNhanVien.setPreferredSize(new java.awt.Dimension(230, 0));

        javax.swing.GroupLayout pn_NVLayout = new javax.swing.GroupLayout(pn_NV);
        pn_NV.setLayout(pn_NVLayout);
        pn_NVLayout.setHorizontalGroup(
            pn_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_NVLayout.createSequentialGroup()
                .addComponent(jLabelNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_NVLayout.setVerticalGroup(
            pn_NVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelNhanVien, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
        );

        pn_TrainCard.setBackground(new java.awt.Color(243, 197, 192));
        pn_TrainCard.setPreferredSize(new java.awt.Dimension(176, 150));
        pn_TrainCard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_TrainCardMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_TrainCardMouseExited(evt);
            }
        });

        jLabelTheTap.setBackground(new java.awt.Color(243, 197, 192));
        jLabelTheTap.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelTheTap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_TrainCard.png"))); // NOI18N
        jLabelTheTap.setText("    Thẻ tập");
        jLabelTheTap.setPreferredSize(new java.awt.Dimension(230, 0));

        javax.swing.GroupLayout pn_TrainCardLayout = new javax.swing.GroupLayout(pn_TrainCard);
        pn_TrainCard.setLayout(pn_TrainCardLayout);
        pn_TrainCardLayout.setHorizontalGroup(
            pn_TrainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TrainCardLayout.createSequentialGroup()
                .addComponent(jLabelTheTap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_TrainCardLayout.setVerticalGroup(
            pn_TrainCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_TrainCardLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelTheTap, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pn_Thue.setBackground(new java.awt.Color(243, 197, 192));
        pn_Thue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_ThueMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_ThueMouseExited(evt);
            }
        });

        jLabelThue.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelThue.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/contract (1).png"))); // NOI18N
        jLabelThue.setText("    Thuê ");
        jLabelThue.setPreferredSize(new java.awt.Dimension(230, 0));

        javax.swing.GroupLayout pn_ThueLayout = new javax.swing.GroupLayout(pn_Thue);
        pn_Thue.setLayout(pn_ThueLayout);
        pn_ThueLayout.setHorizontalGroup(
            pn_ThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ThueLayout.createSequentialGroup()
                .addComponent(jLabelThue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_ThueLayout.setVerticalGroup(
            pn_ThueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_ThueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelThue, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pn_TK.setBackground(new java.awt.Color(243, 197, 192));
        pn_TK.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_TKMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_TKMouseExited(evt);
            }
        });

        jLabelThongKe.setBackground(new java.awt.Color(243, 197, 192));
        jLabelThongKe.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/test.png"))); // NOI18N
        jLabelThongKe.setText("    Thống kê");
        jLabelThongKe.setPreferredSize(new java.awt.Dimension(230, 0));

        javax.swing.GroupLayout pn_TKLayout = new javax.swing.GroupLayout(pn_TK);
        pn_TK.setLayout(pn_TKLayout);
        pn_TKLayout.setHorizontalGroup(
            pn_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TKLayout.createSequentialGroup()
                .addComponent(jLabelThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_TKLayout.setVerticalGroup(
            pn_TKLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelThongKe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
        );

        pn_TaiKhoan.setBackground(new java.awt.Color(243, 197, 192));
        pn_TaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_TaiKhoanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_TaiKhoanMouseExited(evt);
            }
        });

        jLabelTaiKhoan.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabelTaiKhoan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icon/user (1).png"))); // NOI18N
        jLabelTaiKhoan.setText("    Tài khoản");
        jLabelTaiKhoan.setPreferredSize(new java.awt.Dimension(230, 0));

        javax.swing.GroupLayout pn_TaiKhoanLayout = new javax.swing.GroupLayout(pn_TaiKhoan);
        pn_TaiKhoan.setLayout(pn_TaiKhoanLayout);
        pn_TaiKhoanLayout.setHorizontalGroup(
            pn_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_TaiKhoanLayout.createSequentialGroup()
                .addComponent(jLabelTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pn_TaiKhoanLayout.setVerticalGroup(
            pn_TaiKhoanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pn_TaiKhoanLayout.createSequentialGroup()
                .addComponent(jLabelTaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout sideLayout = new javax.swing.GroupLayout(side);
        side.setLayout(sideLayout);
        sideLayout.setHorizontalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Hello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sideLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(pn_Home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_KH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_GT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_HLV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_TrainCard, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
            .addComponent(pn_Thue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_TB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_TT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_TK, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_NV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(pn_TaiKhoan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sideLayout.setVerticalGroup(
            sideLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sideLayout.createSequentialGroup()
                .addComponent(pn_Hello, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_Home, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_KH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pn_GT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_HLV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(pn_TrainCard, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_Thue, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_TB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_TT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pn_TK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_NV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(pn_TaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pn_HLV.getAccessibleContext().setAccessibleParent(side);

        back.add(side, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 700));

        pn_LogOut.setBackground(new java.awt.Color(255, 239, 237));
        pn_LogOut.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pn_LogOut.setForeground(new java.awt.Color(255, 255, 255));
        pn_LogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_LogOutMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pn_LogOutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pn_LogOutMouseExited(evt);
            }
        });

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_logout.png"))); // NOI18N

        jLabel20.setFont(new java.awt.Font("Montserrat", 1, 18)); // NOI18N
        jLabel20.setText("Log - out");
        jLabel20.setPreferredSize(new java.awt.Dimension(230, 0));

        javax.swing.GroupLayout pn_LogOutLayout = new javax.swing.GroupLayout(pn_LogOut);
        pn_LogOut.setLayout(pn_LogOutLayout);
        pn_LogOutLayout.setHorizontalGroup(
            pn_LogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pn_LogOutLayout.setVerticalGroup(
            pn_LogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_LogOutLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pn_LogOutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        back.add(pn_LogOut, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 700, 231, 60));

        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 760));

        jPanelContent.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanelContentLayout = new javax.swing.GroupLayout(jPanelContent);
        jPanelContent.setLayout(jPanelContentLayout);
        jPanelContentLayout.setHorizontalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 860, Short.MAX_VALUE)
        );
        jPanelContentLayout.setVerticalGroup(
            jPanelContentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );

        getContentPane().add(jPanelContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 0, 860, 760));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
   
    
    private void pn_TrainCardMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TrainCardMouseEntered
//        pn_TrainCard.setBackground(Color.white);
    }//GEN-LAST:event_pn_TrainCardMouseEntered

    private void pn_TrainCardMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TrainCardMouseExited
//        pn_TrainCard.setBackground(ori4);
    }//GEN-LAST:event_pn_TrainCardMouseExited

    private void pn_LogOutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LogOutMouseEntered
//        pn_LogOut.setBackground(Color.white);
    }//GEN-LAST:event_pn_LogOutMouseEntered

    private void pn_LogOutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LogOutMouseExited
//        pn_LogOut.setBackground(ori2);
    }//GEN-LAST:event_pn_LogOutMouseExited

    private void pn_LogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_LogOutMouseClicked
        LoginMain click = new LoginMain();
        click.setVisible(true);
        dispose();
    }//GEN-LAST:event_pn_LogOutMouseClicked

    private void jLabelHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseEntered
        
    }//GEN-LAST:event_jLabelHomeMouseEntered

    private void pn_HomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_HomeMouseEntered
//        pn_Home.setBackground(Color.white);
    }//GEN-LAST:event_pn_HomeMouseEntered

    private void pn_KHMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_KHMouseEntered
//        pn_KH.setBackground(Color.white);
    }//GEN-LAST:event_pn_KHMouseEntered

    private void pn_GTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_GTMouseEntered
//        pn_GT.setBackground(Color.white);
    }//GEN-LAST:event_pn_GTMouseEntered

    private void pn_HLVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_HLVMouseEntered
//        pn_HLV.setBackground(Color.white);
    }//GEN-LAST:event_pn_HLVMouseEntered

    private void pn_ThueMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_ThueMouseEntered
//        pn_Thue.setBackground(Color.white);
    }//GEN-LAST:event_pn_ThueMouseEntered

    private void pn_TBMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TBMouseEntered
//        pn_TB.setBackground(Color.white);
    }//GEN-LAST:event_pn_TBMouseEntered

    private void pn_TTMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TTMouseEntered
//        pn_TT.setBackground(Color.white);
    }//GEN-LAST:event_pn_TTMouseEntered

    private void pn_TKMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TKMouseEntered
//        pn_TK.setBackground(Color.white);
    }//GEN-LAST:event_pn_TKMouseEntered

    private void pn_NVMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_NVMouseEntered
//        pn_NV.setBackground(Color.white);
    }//GEN-LAST:event_pn_NVMouseEntered

    private void pn_HomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_HomeMouseExited
//        pn_Home.setBackground(ori4);
    }//GEN-LAST:event_pn_HomeMouseExited

    private void pn_KHMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_KHMouseExited
//        pn_KH.setBackground(ori4);
    }//GEN-LAST:event_pn_KHMouseExited

    private void pn_GTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_GTMouseExited
//        pn_GT.setBackground(ori4);
    }//GEN-LAST:event_pn_GTMouseExited

    private void pn_HLVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_HLVMouseExited
//        pn_HLV.setBackground(ori4);
    }//GEN-LAST:event_pn_HLVMouseExited

    private void pn_ThueMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_ThueMouseExited
//        pn_Thue.setBackground(ori4);
    }//GEN-LAST:event_pn_ThueMouseExited

    private void pn_TBMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TBMouseExited
//        pn_TB.setBackground(ori4);
    }//GEN-LAST:event_pn_TBMouseExited

    private void pn_TTMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TTMouseExited
//        pn_TT.setBackground(ori4);
    }//GEN-LAST:event_pn_TTMouseExited

    private void pn_TKMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TKMouseExited
//        pn_TK.setBackground(ori4);
    }//GEN-LAST:event_pn_TKMouseExited

    private void pn_NVMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_NVMouseExited
//        pn_NV.setBackground(ori4);
    }//GEN-LAST:event_pn_NVMouseExited

    private void pn_TaiKhoanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TaiKhoanMouseEntered
//        pn_TaiKhoan.setBackground(Color.white);
    }//GEN-LAST:event_pn_TaiKhoanMouseEntered

    private void pn_TaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_TaiKhoanMouseExited
//        pn_TaiKhoan.setBackground(ori4);
    }//GEN-LAST:event_pn_TaiKhoanMouseExited

    private void jLabelHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelHomeMouseClicked
        
    }//GEN-LAST:event_jLabelHomeMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws UnsupportedLookAndFeelException {
        UIManager.setLookAndFeel(new FlatLightLaf());
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabelGT;
    private javax.swing.JLabel jLabelHLV;
    private javax.swing.JLabel jLabelHome;
    private javax.swing.JLabel jLabelKhachHang;
    private javax.swing.JLabel jLabelNhanVien;
    private javax.swing.JLabel jLabelTaiKhoan;
    private javax.swing.JLabel jLabelThanhToan;
    private javax.swing.JLabel jLabelTheTap;
    private javax.swing.JLabel jLabelThietBi;
    public javax.swing.JLabel jLabelThongKe;
    private javax.swing.JLabel jLabelThue;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanelContent;
    private javax.swing.JPanel pn_GT;
    private javax.swing.JPanel pn_HLV;
    private javax.swing.JPanel pn_Hello;
    private javax.swing.JPanel pn_Home;
    private javax.swing.JPanel pn_KH;
    private javax.swing.JPanel pn_LogOut;
    private javax.swing.JPanel pn_NV;
    private javax.swing.JPanel pn_TB;
    private javax.swing.JPanel pn_TK;
    private javax.swing.JPanel pn_TT;
    private javax.swing.JPanel pn_TaiKhoan;
    private javax.swing.JPanel pn_Thue;
    private javax.swing.JPanel pn_TrainCard;
    private javax.swing.JPanel side;
    // End of variables declaration//GEN-END:variables
}
