/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import javax.swing.table.DefaultTableModel;
import model.ThietBi;
import DAO.ThietBiDAO;
import java.util.ArrayList;
import javax.swing.*;
import java.awt.Color;
import javax.swing.table.TableRowSorter;
/**
 *
 * @author locmi
 */
public class ThietBiForm extends javax.swing.JPanel {

    private DefaultTableModel model;
    private ArrayList<ThietBi> tb;
    public ThietBiForm() {
        initComponents();
        setSize(860, 760);
        setBackground(new Color (255, 239, 237));
        createTable();
        tb = ThietBiDAO.getInstance().selectAll();
        loadDataToTable(tb);
    }
    
    public final void createTable() {
        model = new DefaultTableModel() {
        @Override
            public boolean isCellEditable(int row, int column) {
            return false;
            }
        };
        String[] headertb = new String[]{"Mã thiết bị", "Tên", "Loại thiết bị", "Số lượng", "Tình trạng" };
        model.setColumnIdentifiers(headertb);
        tb_THIETBI.setModel(model);
    }
    
    public void loadDataToTable(ArrayList<ThietBi> listTB) {
        model.setRowCount(0);
        for (ThietBi tb : listTB) {
            model.addRow(new Object[]{
                tb.getId_TB(), tb.getTenTB(), tb.getLoaiTB(), tb.getSoLuong(), tb.getTinhTrang()
            });
        }
    }

    public void refreshTable() {
        ArrayList<ThietBi> listTB = ThietBiDAO.getInstance().selectAll();
        loadDataToTable(listTB);
    }
    
    private ThietBi getThietBi() {
        int selectedRow = tb_THIETBI.getSelectedRow();
        if (selectedRow == -1) return null;
        String id_TB = tb_THIETBI.getValueAt(selectedRow, 0).toString();
        String tenTB = tb_THIETBI.getValueAt(selectedRow, 1).toString();
        String loaiTB = tb_THIETBI.getValueAt(selectedRow, 2).toString();
        int soluong = Integer.parseInt(tb_THIETBI.getValueAt(selectedRow, 3).toString());
        String tinhtrang = tb_THIETBI.getValueAt(selectedRow, 4).toString();
        
        return new ThietBi(id_TB, tenTB, loaiTB, soluong, tinhtrang);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        tf_SearchBar = new javax.swing.JTextField();
        lb_icSearch = new javax.swing.JLabel();
        lb_Title = new javax.swing.JLabel();
        lb_icAdd = new javax.swing.JLabel();
        lb_icDelete = new javax.swing.JLabel();
        lb_icUpdate = new javax.swing.JLabel();
        lb_icReset = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_THIETBI = new javax.swing.JTable();

        setPreferredSize(new java.awt.Dimension(860, 760));

        back.setBackground(new java.awt.Color(255, 255, 255));

        top.setBackground(new java.awt.Color(251, 129, 54));

        tf_SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_SearchBarActionPerformed(evt);
            }
        });
        tf_SearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_SearchBarKeyReleased(evt);
            }
        });

        lb_icSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Search.png"))); // NOI18N
        lb_icSearch.setToolTipText("");

        lb_Title.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        lb_Title.setForeground(new java.awt.Color(255, 255, 255));
        lb_Title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_Title.setText("QUẢN LÝ THÔNG TIN THIẾT BỊ");

        lb_icAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Insert.png"))); // NOI18N
        lb_icAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_icAddMouseClicked(evt);
            }
        });

        lb_icDelete.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_icDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Delete.png"))); // NOI18N
        lb_icDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_icDeleteMouseClicked(evt);
            }
        });

        lb_icUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/pencil (1) (1).png"))); // NOI18N
        lb_icUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_icUpdateMouseClicked(evt);
            }
        });

        lb_icReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Update.png"))); // NOI18N
        lb_icReset.setPreferredSize(new java.awt.Dimension(32, 32));
        lb_icReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_icResetMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_Title, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(topLayout.createSequentialGroup()
                        .addComponent(tf_SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lb_icSearch)
                        .addGap(213, 213, 213)
                        .addComponent(lb_icAdd)
                        .addGap(45, 45, 45)
                        .addComponent(lb_icDelete)
                        .addGap(43, 43, 43)
                        .addComponent(lb_icUpdate)
                        .addGap(43, 43, 43)
                        .addComponent(lb_icReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 120, Short.MAX_VALUE)))
                .addContainerGap())
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_Title, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tf_SearchBar)
                        .addComponent(lb_icSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lb_icAdd)
                    .addComponent(lb_icDelete)
                    .addComponent(lb_icUpdate)
                    .addComponent(lb_icReset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        tb_THIETBI.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Mã thiết bị", "Tên thiết bị", "Loại thiết bị", "Số lượng", "Tinfh trạng"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb_THIETBI);

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backLayout.createSequentialGroup()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 606, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_SearchBarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SearchBarActionPerformed

    private void tf_SearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_SearchBarKeyReleased
        String searched = tf_SearchBar.getText().trim().toLowerCase();
        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) tb_THIETBI.getModel());
        tb_THIETBI.setRowSorter(sorter);
        
        RowFilter<DefaultTableModel, Object> rowFilter = RowFilter.regexFilter("(?i)" + searched);
        sorter.setRowFilter(rowFilter);
    }//GEN-LAST:event_tf_SearchBarKeyReleased

    private void lb_icAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_icAddMouseClicked
        addThietBi click = new addThietBi(this);
        click.setVisible(true);
    }//GEN-LAST:event_lb_icAddMouseClicked

    private void lb_icDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_icDeleteMouseClicked
        if (tb_THIETBI.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(this, "Chọn thông tin cần xóa!");
    } else {
        ThietBi get = getThietBi();  // Ensure getThietBi() correctly retrieves the selected item
        int check = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa dữ liệu này?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
        
        if (check == JOptionPane.YES_OPTION) {
            int rs = ThietBiDAO.getInstance().delete(get);
            if (rs > 0) {
                JOptionPane.showMessageDialog(this, "Xóa thành công");
                loadDataToTable(ThietBiDAO.getInstance().selectAll());  // Refresh the table with updated data
            } else {
                JOptionPane.showMessageDialog(this, "Xóa thất bại rồi", "Lỗi", JOptionPane.ERROR_MESSAGE);
            }
        }
      }
    }//GEN-LAST:event_lb_icDeleteMouseClicked

    private void lb_icUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_icUpdateMouseClicked
        ThietBi get = getThietBi();
        if (get != null) {
            updateThietBi update = new updateThietBi(this, get);
            update.setVisible(true);
        }
        else JOptionPane.showMessageDialog(this, "Chọn 1 hàng để chỉnh sửa", "Thông báo", JOptionPane.WARNING_MESSAGE);
    }//GEN-LAST:event_lb_icUpdateMouseClicked

    private void lb_icResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_icResetMouseClicked
        refreshTable();
    }//GEN-LAST:event_lb_icResetMouseClicked

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Title;
    private javax.swing.JLabel lb_icAdd;
    private javax.swing.JLabel lb_icDelete;
    private javax.swing.JLabel lb_icReset;
    private javax.swing.JLabel lb_icSearch;
    private javax.swing.JLabel lb_icUpdate;
    private javax.swing.JTable tb_THIETBI;
    private javax.swing.JTextField tf_SearchBar;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
