/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import DAO.ThueDAO;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.RowFilter;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import model.Thue;
import controller.CurrencyUtils;
import java.sql.Date;
import java.text.ParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author locmi
 */
public class ThueForm extends javax.swing.JPanel {
    private DefaultTableModel tblModel;
    private ArrayList<Thue> thue;
    /**
     * Creates new form Thue
     */
    public ThueForm() {
        initComponents();
        UIManager.put("Table.showVerticalLines", true);
        setSize(860, 760);
        setBackground(new Color(255, 239, 237));
        tb_THUE.setDefaultEditor(Object.class, null);
        initTable();
        thue = ThueDAO.getInstance().selectAll();
        loadDataToTable(thue);
    }
    
    public final void initTable() {
        tblModel = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        String[] headerTbl = new String[]{"Mã khách hàng", "Mã huấn luyện viên", "Ngày bắt đầu", "Ngày kết thúc", "Thời gian thuê", "Tổng tiền thuê"};
        tblModel.setColumnIdentifiers(headerTbl);
        tb_THUE.setModel(tblModel);
    }
    
    public void loadDataToTable(ArrayList<Thue> thueList) {
        tblModel.setRowCount(0); 
        for (Thue thue : thueList) {
            tblModel.addRow(new Object[]{
                thue.getId_KH(), thue.getId_HLV(), thue.getNgayBD(), thue.getNgayKT(), thue.getThoiGianThue(), CurrencyUtils.formatCurrency(thue.getTongTien())
            });
        }
    }
    
    public void refreshTableData() {
        ArrayList<Thue> thue = ThueDAO.getInstance().selectAll(); 
        loadDataToTable(thue); 
    }
    
    private Thue getThueSelect() {
        int selectedRow = tb_THUE.getSelectedRow();
        if (selectedRow == -1) return null;
        String id_KH = tb_THUE.getValueAt(selectedRow, 0).toString();
        String id_HLV = tb_THUE.getValueAt(selectedRow, 1).toString();
        Date ngayBD = (Date) tb_THUE.getValueAt(selectedRow, 2);
        Date ngayKT = (Date) tb_THUE.getValueAt(selectedRow, 3);
        int thoiGianThue = Integer.parseInt(tb_THUE.getValueAt(selectedRow, 4).toString());
        String tongTienStr = tb_THUE.getValueAt(selectedRow, 5).toString();
        
        double tongTien = 0;
        try {
            tongTien = CurrencyUtils.parseCurrency(tongTienStr);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        
        return new Thue(id_KH, id_HLV, ngayBD, ngayKT, thoiGianThue, tongTien);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        tf_SearchBar = new javax.swing.JTextField();
        lb_icSearch = new javax.swing.JLabel();
        lb_icAdd = new javax.swing.JLabel();
        lb_icDelete = new javax.swing.JLabel();
        lb_icReset = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lb_Update = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_THUE = new javax.swing.JTable();

        top.setBackground(new java.awt.Color(255, 102, 102));
        top.setPreferredSize(new java.awt.Dimension(100, 180));

        tf_SearchBar.setFont(new java.awt.Font("Montserrat", 0, 12)); // NOI18N
        tf_SearchBar.setToolTipText("");
        tf_SearchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tf_SearchBarFocusGained(evt);
            }
        });
        tf_SearchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_SearchBarActionPerformed(evt);
            }
        });
        tf_SearchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tf_SearchBarKeyReleased(evt);
            }
        });

        lb_icSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Search.png"))); // NOI18N

        lb_icAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Insert.png"))); // NOI18N
        lb_icAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_icAddMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_icAddMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_icAddMouseExited(evt);
            }
        });

        lb_icDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Delete.png"))); // NOI18N
        lb_icDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_icDeleteMouseClicked(evt);
            }
        });

        lb_icReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/ic_Update.png"))); // NOI18N
        lb_icReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_icResetMouseClicked(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Montserrat", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUẢN LÝ THUÊ HUẤN LUYỆN VIÊN");

        lb_Update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/icons/pencil (1) (1).png"))); // NOI18N
        lb_Update.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_UpdateMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(topLayout.createSequentialGroup()
                        .addComponent(tf_SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lb_icSearch)
                        .addGap(79, 79, 79)
                        .addComponent(lb_icAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                        .addComponent(lb_icDelete)
                        .addGap(71, 71, 71)
                        .addComponent(lb_Update)
                        .addGap(73, 73, 73)
                        .addComponent(lb_icReset)
                        .addGap(109, 109, 109))
                    .addGroup(topLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(34, 34, 34))))
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(topLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                        .addComponent(tf_SearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, topLayout.createSequentialGroup()
                        .addGroup(topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_icReset)
                            .addComponent(lb_icDelete)
                            .addComponent(lb_icSearch)
                            .addComponent(lb_icAdd)
                            .addComponent(lb_Update))
                        .addContainerGap())))
        );

        tb_THUE.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Mã khách hàng", "Mã huấn luyện viên", "Ngày bắt đầu", "Ngày kết thúc", "Thời gian thuê", "Tổng tiền thuê"
            }
        ));
        jScrollPane1.setViewportView(tb_THUE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, 860, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tf_SearchBarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tf_SearchBarKeyReleased
//        String searchText = tf_SearchBar.getText().trim().toLowerCase();
//
//        TableRowSorter<DefaultTableModel> sorter = new TableRowSorter<>((DefaultTableModel) tb_THUE.getModel());
//        tb_THUE.setRowSorter(sorter);
//
//        RowFilter<DefaultTableModel, Object> rowFilter = RowFilter.regexFilter("(?i)" + searchText); 
//        sorter.setRowFilter(rowFilter);
    }//GEN-LAST:event_tf_SearchBarKeyReleased

    private void lb_icAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_icAddMouseClicked
        addThue click = new addThue(this);
        click.setVisible(true);
    }//GEN-LAST:event_lb_icAddMouseClicked

    private void lb_icAddMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_icAddMouseEntered
        lb_icAdd.setBackground(Color.white);
    }//GEN-LAST:event_lb_icAddMouseEntered

    private void lb_icAddMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_icAddMouseExited
        lb_icAdd.setBackground(new Color(251,129,54));
    }//GEN-LAST:event_lb_icAddMouseExited

    private void lb_icDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_icDeleteMouseClicked
        if (tb_THUE.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn thẻ tập cần xóa !");
        }
        else {
            Thue select = getThueSelect();
            int chk = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn việc thuê này ?", "Xác nhận xóa thuê ", JOptionPane.YES_NO_OPTION);
            if (chk == JOptionPane.YES_OPTION) {
                int res = ThueDAO.getInstance().delete(select);
                if (res > 0) {
                    JOptionPane.showMessageDialog(this, "Xóa thành công!");
                    loadDataToTable(ThueDAO.getInstance().selectAll());
                }
                else {
                    JOptionPane.showMessageDialog(this, "Xóa thuê thất bại!", "Lỗi", JOptionPane.ERROR_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_lb_icDeleteMouseClicked

    private void lb_icResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_icResetMouseClicked
        refreshTableData();
    }//GEN-LAST:event_lb_icResetMouseClicked

    private void lb_UpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_UpdateMouseClicked
        Thue select = getThueSelect();
        if (select != null) {
            updateThue update = new updateThue(this, select);
            update.setVisible(true);
        }
        else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn để chỉnh sửa.", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_lb_UpdateMouseClicked

    private void tf_SearchBarFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tf_SearchBarFocusGained
        if(tf_SearchBar.getText().equals("Tìm kiếm ..."))
            tf_SearchBar.setText("");
    }//GEN-LAST:event_tf_SearchBarFocusGained

    private void tf_SearchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_SearchBarActionPerformed
        String keyword = tf_SearchBar.getText().trim();
        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập từ khóa tìm kiếm", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Thue thue =  ThueDAO.getInstance().selectById(keyword);
        tblModel.setRowCount(0); 
        
        if (thue != null) {
            Object[] row = {thue.getId_KH(), thue.getId_HLV(), thue.getNgayBD(), thue.getNgayKT(), thue.getThoiGianThue(), CurrencyUtils.formatCurrency(thue.getTongTien())};
            tblModel.addRow(row);
        } else {
            JOptionPane.showMessageDialog(this, "Không tìm thấy dữ liệu", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_tf_SearchBarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_Update;
    private javax.swing.JLabel lb_icAdd;
    private javax.swing.JLabel lb_icDelete;
    private javax.swing.JLabel lb_icReset;
    private javax.swing.JLabel lb_icSearch;
    private javax.swing.JTable tb_THUE;
    private javax.swing.JTextField tf_SearchBar;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
