/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.ThietBiDAO;
import javax.swing.JOptionPane;
import model.ThietBi;

/**
 *
 * @author ADMIN
 */
public class updateThietBi extends javax.swing.JFrame {

    private ThietBiForm panel;
    private ThietBi tb;
/**
     * Creates new form updateThietBi
     */
    updateThietBi(ThietBiForm panel, ThietBi tb) {
        this.tb = tb;
        this.panel = panel;
        initComponents();
        setSize(390, 594);
        setLocationRelativeTo(null);
        tf_MATB.setEditable(false);
        loadData();
    }
    
    private void loadData() {
        tf_MATB.setText(tb.getId_TB());
        tf_TENTB.setText(tb.getTenTB());
        cb_LOAITB.setSelectedItem(tb.getLoaiTB());
        tf_SOLUONG.setText(String.valueOf(tb.getSoLuong()));
        cb_TINHTRANG.setSelectedItem(tb.getTinhTrang());
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        back = new javax.swing.JPanel();
        top = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_MATB = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tf_TENTB = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cb_LOAITB = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        tf_SOLUONG = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        bt_Them = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cb_TINHTRANG = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        back.setBackground(new java.awt.Color(243, 197, 192));

        top.setBackground(new java.awt.Color(255, 102, 102));
        top.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CẬP NHẬT THÔNG TIN THIẾT BỊ");

        javax.swing.GroupLayout topLayout = new javax.swing.GroupLayout(top);
        top.setLayout(topLayout);
        topLayout.setHorizontalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
        );
        topLayout.setVerticalGroup(
            topLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
        );

        jLabel2.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel2.setText("Mã thiết bị");

        jLabel3.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel3.setText("Tên ");

        jLabel4.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel4.setText("Loại thiết bị");

        cb_LOAITB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Strength", "Cardio", "Yoga", " " }));

        jLabel5.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel5.setText("Số lượng");

        tf_SOLUONG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_SOLUONGActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        jLabel6.setText("Tình trạng");

        bt_Them.setBackground(new java.awt.Color(251, 129, 54));
        bt_Them.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        bt_Them.setForeground(new java.awt.Color(255, 255, 255));
        bt_Them.setText("Cập nhật");
        bt_Them.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_ThemMouseClicked(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 16)); // NOI18N
        jButton1.setForeground(new java.awt.Color(251, 129, 54));
        jButton1.setText("Hủy");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cb_TINHTRANG.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tốt", "Hư", "Hỏng" }));

        javax.swing.GroupLayout backLayout = new javax.swing.GroupLayout(back);
        back.setLayout(backLayout);
        backLayout.setHorizontalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(top, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(tf_MATB)
                    .addComponent(tf_TENTB, javax.swing.GroupLayout.DEFAULT_SIZE, 306, Short.MAX_VALUE)
                    .addComponent(cb_LOAITB, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tf_SOLUONG)
                    .addGroup(backLayout.createSequentialGroup()
                        .addComponent(bt_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cb_TINHTRANG, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(41, 41, 41))
        );
        backLayout.setVerticalGroup(
            backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backLayout.createSequentialGroup()
                .addComponent(top, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_MATB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_TENTB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_LOAITB, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tf_SOLUONG, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cb_TINHTRANG, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(backLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bt_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(back, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tf_SOLUONGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_SOLUONGActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_SOLUONGActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bt_ThemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bt_ThemMouseClicked
        String id_TB = tf_MATB.getText();
        String tenTB = tf_TENTB.getText();
        String loaiTB = cb_LOAITB.getSelectedItem().toString();
        String tinhtrang = cb_TINHTRANG.getSelectedItem().toString();
        int soluong;
        try {
            soluong = Integer.parseInt(tf_SOLUONG.getText());
            if (soluong <= 0) {
                JOptionPane.showMessageDialog(this, "Số lượng phải là một số nguyên", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Số lượng phải là một số nguyên dương", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        // Kiểm tra nếu các trường nhập liệu bị bỏ trống
        if (tenTB.isEmpty() || loaiTB.isEmpty() || tinhtrang.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Không được để trống", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
            return;
        }
        ThietBi tb = new ThietBi(id_TB, tenTB, loaiTB, soluong, tinhtrang);

        try {
            // Thêm thiết bị vào cơ sở dữ liệu
            ThietBiDAO.getInstance().update(tb);
            // Tải lại dữ liệu vào bảng
            panel.loadDataToTable(ThietBiDAO.getInstance().selectAll());
            // Hiển thị thông báo thành công
            JOptionPane.showMessageDialog(this, "Cập nhật thiết bị thành công");
            this.dispose();
        } catch (Exception e) {
            // In ra stack trace để giúp tìm lỗi nếu có
            e.printStackTrace();
            // Hiển thị thông báo lỗi chung
            JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi khi thêm thiết bị", "Lỗi", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_bt_ThemMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(updateThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(updateThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(updateThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(updateThietBi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThietBi tb = new ThietBi();
                ThietBiForm panel = new ThietBiForm();
                new updateThietBi(panel, tb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel back;
    private javax.swing.JButton bt_Them;
    private javax.swing.JComboBox<String> cb_LOAITB;
    private javax.swing.JComboBox<String> cb_TINHTRANG;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JTextField tf_MATB;
    private javax.swing.JTextField tf_SOLUONG;
    private javax.swing.JTextField tf_TENTB;
    private javax.swing.JPanel top;
    // End of variables declaration//GEN-END:variables
}
