/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import com.formdev.flatlaf.FlatIntelliJLaf;
import javax.swing.UIManager;
import java.sql.Date;
import model.ThanhToanDetail;
import controller.CurrencyUtils;
import controller.ExportToPDF;
import java.io.File;
import java.text.SimpleDateFormat;
import javax.swing.JFileChooser;


/**
 *
 * @author locmi
 */
public class viewThanhToan extends javax.swing.JFrame {
    private ThanhToanDetail ttoan;
    /**
     * Creates new form viewThanhToan
     */
    public viewThanhToan(ThanhToanDetail ttoan) {
        this.ttoan = ttoan;
        initComponents();
        setLocationRelativeTo(null);
        tf_MATTOAN.setEditable(false);
        tf_MAKH.setEditable(false);
        tf_TENKH.setEditable(false);
        tf_NGAYLAP.setEditable(false);
        tf_TONGTIEN.setEditable(false);
        tf_NGAYTT.setEditable(false);
        tf_TENNV.setEditable(false);
        tf_MANV.setEditable(false);
        loadData();
    }
    
    private void loadData() {
        tf_MATTOAN.setText(ttoan.getId_TTOAN());
        tf_MAKH.setText(ttoan.getId_KH());
        tf_TENKH.setText(ttoan.getTenKH());
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        tf_NGAYLAP.setText(sdf.format(ttoan.getNgayLap()));
        tf_NGAYTT.setText(sdf.format(ttoan.getNgayTT()));
        
        tf_TONGTIEN.setText(CurrencyUtils.formatCurrency(ttoan.getTongTien()));
        tf_TENNV.setText(ttoan.getTenNV());
        tf_MANV.setText(ttoan.getId_NV());

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lb_MANV = new javax.swing.JLabel();
        tf_MATTOAN = new javax.swing.JTextField();
        lb_MANV1 = new javax.swing.JLabel();
        tf_MAKH = new javax.swing.JTextField();
        lb_MANV2 = new javax.swing.JLabel();
        tf_TENKH = new javax.swing.JTextField();
        lb_MANV3 = new javax.swing.JLabel();
        tf_NGAYLAP = new javax.swing.JTextField();
        lb_MANV4 = new javax.swing.JLabel();
        tf_TONGTIEN = new javax.swing.JTextField();
        lb_MANV5 = new javax.swing.JLabel();
        tf_NGAYTT = new javax.swing.JTextField();
        lb_MANV6 = new javax.swing.JLabel();
        tf_TENNV = new javax.swing.JTextField();
        lb_MANV7 = new javax.swing.JLabel();
        tf_MANV = new javax.swing.JTextField();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(243, 197, 192));

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jLabel1.setFont(new java.awt.Font("Montserrat SemiBold", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN THANH TOÁN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
        );

        lb_MANV.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_MANV.setText("Mã thanh toán");

        lb_MANV1.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_MANV1.setText("Tên khách hàng");

        lb_MANV2.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_MANV2.setText("Ngày lập");

        lb_MANV3.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_MANV3.setText("Tổng tiền");

        lb_MANV4.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_MANV4.setText("Ngày thanh toán");

        lb_MANV5.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_MANV5.setText("Mã khách hàng");

        lb_MANV6.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_MANV6.setText("Mã nhân viên thực hiện");

        lb_MANV7.setFont(new java.awt.Font("Montserrat", 1, 16)); // NOI18N
        lb_MANV7.setText("Nhân viên thực hiện");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lb_MANV1)
                                    .addComponent(lb_MANV)
                                    .addComponent(tf_MATTOAN)
                                    .addComponent(tf_MAKH)
                                    .addComponent(tf_TENKH, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lb_MANV5))
                            .addComponent(tf_MANV, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 146, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lb_MANV2)
                                    .addComponent(tf_NGAYLAP)
                                    .addComponent(lb_MANV3)
                                    .addComponent(tf_TONGTIEN)
                                    .addComponent(lb_MANV4)
                                    .addComponent(tf_NGAYTT, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(146, 146, 146)
                                .addComponent(tf_TENNV))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(lb_MANV6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lb_MANV7)
                        .addGap(68, 68, 68)))
                .addGap(82, 82, 82))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_MANV)
                    .addComponent(lb_MANV2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_MATTOAN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_NGAYLAP, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_MANV3)
                    .addComponent(lb_MANV5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_MAKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_TONGTIEN, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_MANV1)
                    .addComponent(lb_MANV4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_TENKH, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_NGAYTT, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_MANV6)
                    .addComponent(lb_MANV7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tf_MANV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_TENNV, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(57, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            UIManager.setLookAndFeel(new FlatIntelliJLaf());
        } catch( Exception ex ) {
            System.err.println( "Failed to initialize LaF" );
        }

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ThanhToanDetail ttoan = new ThanhToanDetail();
                new viewThanhToan(ttoan).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_MANV;
    private javax.swing.JLabel lb_MANV1;
    private javax.swing.JLabel lb_MANV2;
    private javax.swing.JLabel lb_MANV3;
    private javax.swing.JLabel lb_MANV4;
    private javax.swing.JLabel lb_MANV5;
    private javax.swing.JLabel lb_MANV6;
    private javax.swing.JLabel lb_MANV7;
    private javax.swing.JTextField tf_MAKH;
    private javax.swing.JTextField tf_MANV;
    private javax.swing.JTextField tf_MATTOAN;
    private javax.swing.JTextField tf_NGAYLAP;
    private javax.swing.JTextField tf_NGAYTT;
    private javax.swing.JTextField tf_TENKH;
    private javax.swing.JTextField tf_TENNV;
    private javax.swing.JTextField tf_TONGTIEN;
    // End of variables declaration//GEN-END:variables
}
